name: CI/CD

on:
  push:
    tags:
      - '*'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/joonhwan.org:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/joonhwan.org:latest

      - name: Deploy to VPS
        run: |
          ssh user@vps "docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/joonhwan.org:latest && docker run -d --restart always --name myapp -p 80:80 ghcr.io/${{ secrets.GHCR_USERNAME }}/joonhwan.org:latest"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}